export const regions = {
  HK: {
    name: "Hong Kong",
    divisions: {
      "HK-HK": "香港島",
      "HK-KLN": "九龍",
      "HK-NT": "新界",
    },
  },
  TW: {
    name: "台灣",
    divisions: {
      "TW-KHH": "高雄市",
      "TW-TPE": "臺北市",
      "TW-CYI": "嘉義市",
      "TW-HSZ": "新竹市",
      "TW-KEE": "基隆市",
      "TW-TXG": "臺中市",
      "TW-TNN": "臺南市",
      "TW-CHA": "彰化縣",
      "TW-HUA": "花蓮縣",
      "TW-ILA": "宜蘭縣",
      "TW-MIA": "苗栗縣",
      "TW-NAN": "南投縣",
      "TW-PEN": "澎湖縣",
      "TW-PIF": "屏東縣",
      "TW-TTT": "臺東縣",
      "TW-TAO": "桃園市",
      "TW-YUN": "雲林縣",
      "TW-JIN": "金門縣",
      "TW-XIN": "新北市",
      "TW-LIAN": "連江縣",
    },
  },
};
export const divisions = [
  "HK-HK",
  "HK-KLN",
  "HK-NT",
  "TW-KHH",
  "TW-TPE",
  "TW-CYI",
  "TW-HSZ",
  "TW-KEE",
  "TW-TXG",
  "TW-TNN",
  "TW-CHA",
  "TW-HUA",
  "TW-ILA",
  "TW-MIA",
  "TW-NAN",
  "TW-PEN",
  "TW-PIF",
  "TW-TTT",
  "TW-TAO",
  "TW-YUN",
  "TW-JIN",
  "TW-XIN",
  "TW-LIAN",
];
